spring:
  application:
    name: dimdim-pedidos
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: never
server:
  port: ${PORT:8080}
  error:
    include-message: never
    include-stacktrace: never
dimdim:
  timezone: ${APP_TIMEZONE:America/Sao_Paulo}
